[package]
name        = "steviegoodman/site-74"
description = "Next generation SCP roleplay game under active development."
version     = "1.0.0"
registry    = "https://github.com/UpliftGames/wally-index"
realm       = "shared"

[dependencies]
Knit = "sleitnick/knit@1.5.1"
Observers = "sleitnick/observers@0.3.3"
Component = "sleitnick/component@2.4.6"
Signal = "sleitnick/signal@1.5.0"
TableUtil = "sleitnick/table-util@1.2.0"
ProfileService = "surnautica/profileservice@1.0.0"
Roact = "roblox/roact@1.4.4"
Cmdr = "evaera/cmdr@1.12.0"
Promise = "evaera/promise@4.0.0"
Waiter = "steviegoodman/waiter@4.0.1"
WaiterV5 = "steviegoodman/waiter@5.0.1"