[package]
name        = "steviegoodman/site-74"
description = "Next generation SCP roleplay game under active development."
version     = "1.0.0"
registry    = "https://github.com/UpliftGames/wally-index"
realm       = "shared"

[dependencies]
Knit           = "sleitnick/knit@1.5.1"
Observers      = "sleitnick/observers@0.3.3"
Component      = "sleitnick/component@2.4.6"
Option         = "sleitnick/option@1.0.4"
Signal         = "sleitnick/signal@1.5.0"
EnumList       = "sleitnick/enum-list@2.0.1"
TableUtil      = "sleitnick/table-util@1.2.0"
WaitFor        = "sleitnick/wait-for@0.2.2"
ProfileService = "surnautica/profileservice@1.0.0"
Roact          = "roblox/roact@1.4.4"
Cmdr           = "evaera/cmdr@1.12.0"
Promise        = "evaera/promise@4.0.0"