[package]
name = "steviegoodman/waiter"
description = "Have your Roblox hierarchy instances served to you with convenience!"
version = "6.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["**"]
include = [
    "src",
    "src/init.lua",
    "default.project.json",
    "wally.toml"
]

[dependencies]
TableUtil = "sleitnick/table-util@1.2.0"

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"